#!/usr/bin/env zsh

# `.zlogin' is sourced in login shells. It should contain commands that should
# be executed only in login shells. `.zlogin' is not the place for alias
# definitions, options, environment variable settings, etc.; as a general rule,
# it should not change the shell environment at all. Rather, it should be used
# to set the terminal type and run a series of external commands (fortune, msgs,
# etc).
# (source: http://zsh.sourceforge.net/Intro/intro_3.html)
#
# This is the local `.zlogin' file. It is intended to contain run commands
# applicable only to this machine. These commands will override conflicting
# commands in the corresponding global `.zlogin' file.
#
# $HOME/.zlogin should link to this file.

# Apply global commands
source $DOTFILES_ROOT'/config/global/runcom/zsh/zlogin'

# Apply local commands. Anything beyond this point should only apply to this
# machine.
