#!/usr/bin/env zsh

# `.zprofile' is similar to `.zlogin', except that it is sourced before
# `.zshrc'. `.zprofile' is meant as an alternative to `.zlogin' for ksh fans;
# the two are not intended to be used together, although this could certainly
# be done if desired.
# (source: http://zsh.sourceforge.net/Intro/intro_3.html)
#
# This is the local `.zprofile' file. It is intended to contain run commands
# applicable only to this machine. These commands will override conflicting
# commands in the corresponding global `.zprofile' file.
#
# $HOME/.zprofile should link to this file.

# Apply global commands
source $DOTFILES_ROOT'/config/global/runcom/zsh/zprofile'

# Apply local commands. Anything beyond this point should only apply to this
# machine.
