#!/usr/bin/env zsh

# `.zshenv' is sourced on all invocations of the shell, unless the -f option is
# set. It should contain commands to set the command search path, plus other
# important environment variables. `.zshenv' should not contain commands that
# produce output or assume the shell is attached to a tty.
# (source: http://zsh.sourceforge.net/Intro/intro_3.html)
#
# This is the local `.zshenv' file. It is intended to contain run commands
# applicable only to this machine. These commands will override conflicting
# commands in the corresponding global `.zshenv' file.
#
# $HOME/.zshenv should link to this file.

export DOTFILES_ROOT={{dotfiles_root}}

# Apply global commands
source $DOTFILES_ROOT'/global/runcom/zsh/zshenv'

# Apply local commands. Anything beyond this point should only apply to this
# machine.
