#!/usr/bin/env zsh

# `.zshrc' is sourced in interactive shells. It should contain commands to set
# up aliases, functions, options, key bindings, etc.
# (source: http://zsh.sourceforge.net/Intro/intro_3.html)
#
# This is the local `.zshrc' file. It is intended to contain run commands
# applicable only to this machine. These commands will override conflicting
# commands in the corresponding global `.zshrc' file.
#
# $HOME/.zshrc should link to this file.

# Apply global commands
source $DOTFILES_ROOT'/global/runcom/zsh/zshrc'

# Apply local commands. Anything beyond this point should only apply to this
# machine.
