#!/usr/bin/env zsh

# `.zprofile' is similar to `.zlogin', except that it is sourced before
# `.zshrc'. `.zprofile' is meant as an alternative to `.zlogin' for ksh fans;
# the two are not intended to be used together, although this could certainly
# be done if desired.
# (source: http://zsh.sourceforge.net/Intro/intro_3.html)
#
# This is the global `.zprofile' file. It is intended to contain run commands
# common to all machines. These commands can be overridden on a per-machine
# basis in the corresponding local `.zprofile' file.

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"
